[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "example_package_carlos_ds730"
version = "0.0.1"
authors = [
  { name="Carlos Fernández", email="author@example.com" },
]
description = "A small example package"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/carlosds731/example_package_carlos_ds730"
"Bug Tracker" = "https://github.com/carlosds731/example_package_carlos_ds730/issues"